# -*- coding: utf-8 -*-
"""JudgingApp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13SZeZYg3mrQqQUxJW9UXBN3fVlAipZgb
"""

# -*- coding: utf-8 -*-
"""judge_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c0n26yqUWs_FmGS0Hlt1WzZJ3LlhoJ6k
"""

import csv
from urllib.request import urlopen
from bs4 import BeautifulSoup
from google.colab import auth
auth.authenticate_user()
import re

import gspread
from google.auth import default
creds, _ = default()


baseUrl = 'https://hacknc2021.devpost.com/'
subsUrl = baseUrl + 'project-gallery?page='

def main():
    count = 1
    fieldsList = []
    while(count < 3):
      subsObj = BeautifulSoup(urlopen(subsUrl + str(count)), 'html.parser')
      submissions = subsObj.find_all('a', {'class':'block-wrapper-link fade link-to-software'})
      if len(submissions) != 0:
            subnum = 0
            for submission in submissions:
                subUrl = submission.attrs['href']
                subObj = BeautifulSoup(urlopen(subUrl), 'html.parser')
                title = getTitle(subObj)
                link = getLink(subObj, subUrl)
                subtitle = getSubtitle(subObj, title)
                members = getMembers(subObj)
                builtWith = getBuiltWith(subObj)
                fieldsList.append([title.get_text().strip(), link.get('href'), subtitle.get_text().strip(), ', '.join(members), ', '.join(builtWith)])
                subnum += 1    
            count = count + 1
    exportToGoogleSheets(fieldsList)


def getTitle(subObj):
    title = subObj.find('h1', {'id':'app-title'})
    return title

def getLink(subObj, subUrl):
    link = subObj.find('a', href=re.compile('https://devpost.com/software/'))
    return link

def getSubtitle(subObj, title):
    subtitle = title.parent.find('p')
    return subtitle

def getMembers(subObj):
  memberList = []
  members = subObj.find('section',{'id':'app-team'}).findAll('a',{'class':'user-profile-link'})
  for member in members:
    memberList.append(member.get_text().strip())
  while ("" in memberList):
    memberList.remove("")
  return memberList


def getBuiltWith(subObj):
    builtWithList = []
    try:
        builtWith = subObj.find('div', {'id':'built-with'}).findAll('span', {'class':'cp-tag'})
        for tool in builtWith:
            builtWithList.append(tool.get_text().strip())
    except:
        print('No Tools Found')
    return builtWithList

def getTrack(subObj):
  track = subObj.find('div',{'class':'panel'}).find('label',{'class':'checkbox','checked':'checked'})


def exportToGoogleSheets(fieldsList):

  gc = gspread.authorize(creds)

  sh = gc.create('A new spreadsheet')

  # Open our new sheet and add some data.
  worksheet = gc.open('A new spreadsheet').sheet1
  
  i = 0
  x = 0
  j = 0
  k = 0
  l = 0
  cell_list = worksheet.range('A2:A35')
  cell_list2 = worksheet.range('B2:B35')
  cell_list3 = worksheet.range('C2:C35')
  cell_list4 = worksheet.range('D2:D35')
  cell_list5 = worksheet.range('E2:E35')

  for cell in cell_list:
      cell.value = fieldsList[i][0]
      i = i+1

  for cell in cell_list2:
      cell.value = fieldsList[x][1]
      x = x+1

  for cell in cell_list3:
     cell.value = fieldsList[j][2]
     j = j+1

  for cell in cell_list4:
      cell.value = fieldsList[k][3]
      k = k+1

  for cell in cell_list5:
      cell.value = fieldsList[l][4]
      l = l+1

  worksheet.update_cells(cell_list)
  worksheet.update_cells(cell_list2)
  worksheet.update_cells(cell_list3)
  worksheet.update_cells(cell_list4)
  worksheet.update_cells(cell_list5)

  gameList = []
  toolsList = []
  webList = []
  miscList = []

  i = 0
  while i < len(fieldsList):
    if "game" in fieldsList[i][2]:
        gameList.append(fieldsList[i])
    elif "learn" or "teach" or "tool" or "help" or "education" in fieldsList[i][2]:
        toolsList.append(fieldsList[i])
    elif "web" or "online" or "internet" in fieldsList[i][2]:
        webList.append(fieldsList[i])
    else:
        miscList.append(fieldsList[i])
    i += 1

  print(len(gameList))
  print(len(toolsList))
  print(len(webList))
  print(len(miscList))

main()