# -*- coding: utf-8 -*-
"""updated_judgingapp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fXu4dtT0fSvGo5cgYToYdggywa7cfy1K
"""

!pip install xlsxwriter

# -*- coding: utf-8 -*-
"""judge_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c0n26yqUWs_FmGS0Hlt1WzZJ3LlhoJ6k
"""

# import required libraries
import pandas as pd
import csv
from urllib.request import urlopen
from bs4 import BeautifulSoup
from google.colab import auth
auth.authenticate_user()
import re

import gspread
from google.auth import default
creds, _ = default()

# create variable to store url to hackathon devpost page
baseUrl = 'https://mhacks6.devpost.com/'
subsUrl = baseUrl + 'project-gallery?page='

def main():
    count = 1
    # create a list for storing web-scraped data
    fieldsList = []
    while(count < 3):
      # create parse tree of information from the above url
      subsObj = BeautifulSoup(urlopen(subsUrl + str(count)), 'html.parser')
      # return a list of submissions from parse trees
      submissions = subsObj.find_all('a', {'class':'block-wrapper-link fade link-to-software'})
      if len(submissions) != 0:
            subnum = 0
            # create and append a list containing a project's information (name, description, link, members, and technology used) to the list created above
            for submission in submissions:
                subUrl = submission.attrs['href']
                subObj = BeautifulSoup(urlopen(subUrl), 'html.parser')
                title = getTitle(subObj)
                link = getLink(subObj, subUrl)
                subtitle = getSubtitle(subObj, title)
                members = getMembers(subObj)
                builtWith = getBuiltWith(subObj)
                fieldsList.append([title.get_text().strip(), link.get('href'), subtitle.get_text().strip(), ', '.join(members), ', '.join(builtWith)])
                subnum += 1    
            count = count + 1
    # export the list above into 
    exportToGoogleSheets(fieldsList)

 
def getTitle(subObj):
    title = subObj.find('h1', {'id':'app-title'})
    return title

def getLink(subObj, subUrl):
    link = subObj.find('a', href=re.compile('https://devpost.com/software/'))
    return link

def getSubtitle(subObj, title):
    subtitle = title.parent.find('p')
    return subtitle

def getMembers(subObj):
  memberList = []
  members = subObj.find('section',{'id':'app-team'}).findAll('a',{'class':'user-profile-link'})
  for member in members:
    memberList.append(member.get_text().strip())
  while ("" in memberList):
    memberList.remove("")
  return memberList


def getBuiltWith(subObj):
    builtWithList = []
    try:
        builtWith = subObj.find('div', {'id':'built-with'}).findAll('span', {'class':'cp-tag'})
        for tool in builtWith:
            builtWithList.append(tool.get_text().strip())
    except:
        print('No Tools Found')
    return builtWithList

def getTrack(subObj):
  track = subObj.find('div',{'class':'panel'}).find('label',{'class':'checkbox','checked':'checked'})


def exportToGoogleSheets(fieldsList):

  gc = gspread.authorize(creds)

  sh = gc.create('A new spreadsheet')

  # Open our new sheet and add some data.
  worksheet = gc.open('A new spreadsheet').sheet1
  judges = gc.open('judge_mockup_sheet').sheet1


  judge_name = judges.range('B2:B15')
  judge_pronouns = judges.range('C2:C15')
  judge_sponsor = judges.range('D2:D15')
  judge_industry = judges.range('E2:E15')
  judge_techstack = judges.range('F2:F15')

  
  i = 0
  x = 0
  j = 0
  k = 0
  l = 0
  m = 0
  n = 0
  #cell titles
  
  cell_field = worksheet.range('A1:G1')
  cell_field[0].value='Title'
  cell_field[1].value='Link'
  cell_field[2].value='Description'
  cell_field[3].value='Members'
  cell_field[4].value='Technologies used'
  cell_field[5].value='Category'
  cell_field[6].value='Track'

  cell_list = worksheet.range('A2:A35')
  cell_list2 = worksheet.range('B2:B35')
  cell_list3 = worksheet.range('C2:C35')
  cell_list4 = worksheet.range('D2:D35')
  cell_list5 = worksheet.range('E2:E35')
  cell_list6 = worksheet.range('F2:F35')
  cell_list7 = worksheet.range('G2:G35')
  




  for cell in cell_list:
      cell.value = fieldsList[i][0]
      i = i+1

  for cell in cell_list2:
      cell.value = fieldsList[x][1]
      x = x+1

  for cell in cell_list3:
     cell.value = fieldsList[j][2]
     j = j+1

  for cell in cell_list4:
      cell.value = fieldsList[k][3]
      k = k+1

  for cell in cell_list5:
      cell.value = fieldsList[l][4]
      l = l+1

  df = pd.read_csv("data.csv", usecols = ['sponsors','category'], encoding="latin-1")
  df['sponsors'] = df['sponsors'].fillna('N/A')
  df['category'] = df['category'].fillna('Miscellaneous')

  for cell in cell_list6:
    cell.value = df['category'][m]
    m = m + 1
 
  for cell in cell_list7:
    cell.value = df['sponsors'][n]
    n = n + 1


  #create dictionary with keys as subjects and lists of judges as value
  worksheet.update_cells(cell_field)
  worksheet.update_cells(cell_list)
  worksheet.update_cells(cell_list2)
  worksheet.update_cells(cell_list3)
  worksheet.update_cells(cell_list4)
  worksheet.update_cells(cell_list5)
  worksheet.update_cells(cell_list6)
  worksheet.update_cells(cell_list7)

main()

from google.colab import drive
drive.mount('/content/drive/')